language: ruby
rvm:
  - 1.9.3
before_install:
  - git submodule update --init --recursive
before_script:
  - 'bundle exec start_services'
  - sudo apt-get install nmap
  - sudo apt-get install wget
  - sudo apt-get install libcurl4-openssl-dev
  - 'cd vendor && wget http://downloads.sourceforge.net/project/dirb/dirb/2.03/dirb203.tar.gz && tar xvfz dirb203.tar.gz && cd dirb && ./configure && make && sudo cp dirb /usr/local/bin/ && cd ../../'
  - export DIRB_WORDLISTS="/home/travis/build/gauntlt/gauntlt/vendor/dirb/wordlists"
script:
  - 'bundle exec gauntlt -t @final'
notifications:
  irc:
    channels:
      - "chat.freenode.net#gauntlt"
    use_notice: true
